### ISSUE TITLE
External database issue.

### ISSUE THREAD

**Issue by Menphis88** [KaiKikuchi/UUIDProvider#1]
Is it possible that, if the plugins (any of your database requirering plugins), cannot connect to an external database, then uses localhost?

I have had database issues before and found out that your plugins do not like dns names. It simply requires a real numerical ip.

But now that i use numerical ip's only the logs say it cannot connect to the local ip, but thats not the one that i actually defined in the config.

http://prntscr.com/8tb674

Talked to the serverhosts, and they blame the plugin. But i still think its their messed up setup that wont allow for  external mysql connections. Because all of your plugins has worked fine for me in the past.

Just hoping that you may know the answer or can agree that its the hosts fault.

//Mark

**Comment by KaiKikuchi** [comment]
Hello. DeVcoFTB has 5 servers and use the same database. One of these servers is in France, the other 4 servers are in Canada. We have no connection issues, and we use a DNS name. Our provider is OVH.
Also, UUIDProvider has an internal cache loaded in memory. There aren't so many MySQL requests frequently.

Anyway, UUIDProvider 2 is coming out along with BetterOnTime 1.6.
Are you using any other plugin that uses UUIDProvider?

**Comment by Menphis88** [comment]
Yeah im trying to get, Sync, Betterontime, and GriefpreventionPlus to work.

Anyhow, it simply has to be the hosts setup thats messed up, i dont see any other solution.

Thanks for the quick response

**Comment by Menphis88** [comment]
Okay so i figured out the issue, and thought i would share it in here.
So when making users on mysql you have to ofc use the % wildcard (as host) to allow access from any remote host.
