### ISSUE TITLE
Support for FastLogin

### ISSUE THREAD

**Issue by Eufranio** [KaiKikuchi/UUIDProvider#2]
For us that runs servers with FastLogin, it allows premium players log in with a premium UUID, and cracked players with an cracked UUID (allowing nick changes and etc). The problem is that UUIDProvider can provide only 1 of the options, or cracked or premium. If we choose cracked, premium players won't be known for the plugin, if we choose premium, cracked players won't be able to join...

**Comment by KaiKikuchi** [comment]
Hello. Please try this: https://github.com/KaiKikuchi/UUIDProvider/releases/tag/v.2.5-DEV

Enable the "dummy mode" on the config by specifying:
`DummyMode: true`

Let me know if this helps.

**Comment by Eufranio** [comment]
It works now, thanks.
