### ISSUE TITLE
UUIDProvider 2.5.1 not working as intended

### ISSUE THREAD

**Issue by CobaltSparkz** [KaiKikuchi/UUIDProvider#3]
Hey Kai,

I've not changed anything recently, aside from updating to the most recent version of UUIDProvider, as well as add KaiCommons. Now, over the last 10 days or so, a lot of players are being denied access upon joining, with the error message "Invalid UUID or Mojang's servers down. Try later."

Now, this isn't the case, as Mojang's servers are fine - It's something in the network somewhere that's not working as intended.

From console, "WARN [UUIDProvider] UUIDProvider couldn't retrieve UUID for (Username) - Then shows the usual garbage after someone can't connect due to that error. 

Any idea what's going on?

**Comment by KaiKikuchi** [comment]
Hello. Is your server allowing players without a legal copy of Minecraft?

**Comment by CobaltSparkz** [comment]
No, we do not - therefore the offline-mode option is set to 'false'. 

Cheers

**Comment by spannerman79** [comment]
https://twitter.com/MojangStatus/status/874217954623332352

**Comment by CobaltSparkz** [comment]
Hey Spanner - It's been like this for 10 days, maybe more, I only found out after a player finally told me they were still having this issue

**Comment by spannerman79** [comment]
Doesn't look to be a code issue ( https://github.com/KaiKikuchi/UUIDProvider/blob/master/src/main/java/net/kaikk/mc/uuidprovider/NameFetcher.java#L38 ) as it is still the correct API end point. ( [Reference](http://wiki.vg/Mojang_API#UUID_-.3E_Profile_.2B_Skin.2FCape) )

I'd say you need to check via curl on your end first if you have issues accessing `https://sessionserver.mojang.com/session/minecraft/profile/<uuid>` - replace `<uuid>` with your own uuid if you wish

@KaiKikuchi do you implement cache? Mojang's API is heavily rate limited.

I'd say there is something in your network that is heavily hitting Mojang's API @CobaltSparkz - which @KaiKikuchi cannot do anything about - unless it is one of his plugins.

**Comment by KaiKikuchi** [comment]
@spannerman79 is correct. The whole point of UUIDProvider is the caching system that helps a lot for networks that are hosting multiple servers in the same machine. Other than UUIDProvider, none of my other plugins use the MojangAPI directly. They all use UUIDProvider that provides a cache with very fast requests. UUIDProvider implements 2 caching systems: in-memory cache, and MySQL database cache.

@CobaltSparkz Your issue can be caused by several things:
- As @spannerman79 said, you may have other plugins accessing the Mojang API that are causing the issue for UUIDProvider
- If you have multiple servers, be sure to use the same UUIDProvider MySQL database for all your servers!

**Comment by CobaltSparkz** [comment]
Hey @KaiKikuchi @spannerman79 - They're all running on the same UUIDProvider DB - It has been running fine until the last 10-14 days, that I'm aware of, which is weird, as nothing's changed - I'll have a poke around and see what else is "calling" upon Mojang - Is there a way to see if I'm hitting the limit?

**Comment by spannerman79** [comment]
> Is there a way to see if I'm hitting the limit?

I already gave an example as to how

> I'd say you need to check via curl on your end first if you have issues accessing `https://sessionserver.mojang.com/session/minecraft/profile/<uuid>` - replace `<uuid>` with your own uuid if you wish

**Comment by CobaltSparkz** [comment]
Sorry - Whilst I may run and maintain the minecraft network, my knowledge of linux/java/curl and whatnot is limited at best - Could you perhaps give a basic tutorial/send me in the right direction? Apologies

**Comment by KaiKikuchi** [comment]
You can do what @spannerman79 told you.

By using your server, go to https://api.mojang.com/users/profiles/minecraft/KaiNoMood

If you're using a Windows Server, just use Internet Explorer or similar.

If you're using linux, try with `wget https://api.mojang.com/users/profiles/minecraft/KaiNoMood` then use `cat KaiNoMood`

**Comment by CobaltSparkz** [comment]
@KaiKikuchi http://prntscr.com/fkyf13 is the return upon running the above command

**Comment by KaiKikuchi** [comment]
The HTTP error 429 is "Too many requests". This means your server is making too many requests to Mojang.

**Comment by CobaltSparkz** [comment]
Alrighty, not sure what's changed, so I'll have to trawl through my list of plugins as I have 0 technical knowhow of being able to check through console/commands. Thank you both for your time and assistance @KaiKikuchi @spannerman79

**Comment by CobaltSparkz** [comment]
https://www.reddit.com/r/admincraft/comments/6hu5i8/mojang_api_blanket_blocking_ip_subnets/

Looks to be this.

**Comment by spannerman79** [comment]
Hm, I have both OVH & Linode and yet I don't suffer from this issue.

Either way outside the scope of this issue tracker

**Comment by CobaltSparkz** [comment]
Yep, just wanted to let you know :)
